function Hd = bandstopIIR(Fs,Fpass1,Fstop1,Fstop2,Fpass2)
%BANDSTOPIIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 04-Jan-2018 22:04:10

% Elliptic Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
%Fs = 48000;  % Sampling Frequency

%Fpass1 = 7200;    % First Passband Frequency
%Fstop1 = 9600;    % First Stopband Frequency
%Fstop2 = 12000;   % Second Stopband Frequency
%Fpass2 = 14400;   % Second Passband Frequency
Apass1 = 1;       % First Passband Ripple (dB)
Astop  = 60;      % Stopband Attenuation (dB)
Apass2 = 1;       % Second Passband Ripple (dB)
match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
